# Generated by Django 3.1.7 on 2021-04-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('variety', models.CharField(max_length=50)),
                ('aln', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('pub_date', models.DateField()),
                ('image', models.FileField(null=True, upload_to='', verbose_name='')),
            ],
        ),
    ]
